name: TEST

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: run pwd
        run: pwd

      - name: run ls -al
        run: ls -al

      - name: use variable
        run: echo "${{vars.TEST}}"