name: TEST

on:
  push:
    branches: [test]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: run pwd
        run: pwd

      - name: run ls -al
        run: ls -al

      - name: new variable test
        run: echo "${{vars.TEST}}"